name: mlflow-docker-testing
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: sanity-check
        env:
          repo_token: ${{ secrets.REPO_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install mlflow
          docker build -t mlflow-docker-example -f Dockerfile .
          mlflow run .
          #pip install -r requirements.txt
          #python test.py