name: mlflow-docker-testing
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: sanity-check
        env:
          repo_token: ${{ secrets.REPO_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          # docker build -t mlflow-docker-example -f Dockerfile .
          mlflow run . --no-conda
          #mlflow ui
          git config --global user.email "kethansarma@gmail.com"
          git add . && git commit -m "Mlflow" && git push
          #pip install -r requirements.txt
          #python test.py