name: mlflow-docker-testing
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: sanity-check
        env:
          repo_token: ${{ secrets.REPO_TOKEN }}
        run: |
          # Your ML workflow goes here
          # sudo apt-get update && sudo apt-get upgrade
          # sudo apt-get install python3.7
          # pip install mlflow
          pip install -r requirements.txt
          # docker build -t mlflow-docker-example -f Dockerfile .
          mlflow run . --no-conda
          #pip install -r requirements.txt
          #python test.py